### ISSUE TITLE
Ability to extend the properties to convert

### ISSUE THREAD

**Issue by MohammadYounes** [jakob101/postcss-inline-rtl#4]
RTLCSS gives you the ability to change none directional properties using directives, for example:

``` css
.example { content: "A"/*rtl:"B"*/;}
```

With the current implementation, such properties will be ignored. Having the ability to extend the list of properties to convert would solve this.

In case you will add this, the [check](https://github.com/jakob101/postcss-inline-rtl/blob/master/index.js#L103) need to account for changes in the raw value (changing the raw value instead of value maintains original formatting).

``` js
var rtlValue = rtlDecl.raws.value && rtlDecl.raws.value.raw ? rtlDecl.raws.value.raw : rtlDecl.value;
if (rtlDecl.prop !== decl.prop ||
    rtlValue !== decl.value) { ...
```

Thanks!

**Comment by jakob101** [comment]
checkout #6, this means I would support all rtlcss directives. What do you think?

**Comment by MohammadYounes** [comment]
Cool, I tried both on bootstrap and the performance didn't differ much. 

With props filter (including content) `435ms` and without `455ms` :+1:

**Comment by jakob101** [comment]
Great! Merged :)
